version: '2.0'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    command: >
      bash -c "set -ex;
               echo "[####################################################################################################################]";
               npm install --save-dev;
               echo "[####################################################################################################################]";
               npm start"
    volumes:
    - .:/app
    ports:
    - "9000:9000"
    networks:
    - dev
networks:
  dev:
    driver: bridge


# docker-compose exec mysql mysql -u root  -e 'create database formlogin' -p
# docker-compose exec node bash
# docker-compose exec mysql mysql -p

# docker ps -a
# docker-compose up -d
# docker-compose up
# use containers name to access them by network
