FROM node:lts

# Set working directory
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    unzip \
    git \
    curl

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# install global 
RUN npm install -g typescript

# Change current user to www
USER node

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["node","server.js]
